import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="main flex col-flex">
        <h1>WELCOME!</h1>
        <h2>To The Home Page 😀</h2>
      </div>
    </>
  );
}
